CREATE TABLE Z88116.BANK_TRANSACTIONS (
    ACCOUNT_ID    VARCHAR(10)   NOT NULL,
    CUSTOMER_NAME VARCHAR(30)   NOT NULL,
    TX_AMOUNT     DECIMAL(11,2) NOT NULL,
    TX_TYPE       CHAR(2)       NOT NULL,
    TX_DATE       DATE          NOT NULL,
    STATUS        VARCHAR(15)   NOT NULL DEFAULT 'NORMAL',
    PRIMARY KEY (ACCOUNT_ID, TX_DATE)
) IN DATABASE Z88116;