CREATE TABLE Z88116.BANK_TRANSACTIONS (
    ACCOUNT_ID    VARCHAR(10)   NOT NULL,
    CUSTOMER_NAME VARCHAR(30)   NOT NULL,
    TX_AMOUNT     DECIMAL(11,2) NOT NULL,
    TX_TYPE       CHAR(2)       NOT NULL,
    TX_DATE       DATE          NOT NULL,
    STATUS        VARCHAR(15)   NOT NULL DEFAULT 'NORMAL',
    PRIMARY KEY (ACCOUNT_ID, TX_DATE)
) IN DATABASE Z88116;

INSERT INTO Z88116.BANK_TRANSACTIONS (ACCOUNT_ID, CUSTOMER_NAME, TX_AMOUNT, TX_TYPE, TX_DATE, STATUS)
VALUES ('ACC10001', 'BOOLEAN', 15500.50, 'DR', CURRENT DATE, 'NORMAL');

INSERT INTO Z88116.BANK_TRANSACTIONS (ACCOUNT_ID, CUSTOMER_NAME, TX_AMOUNT, TX_TYPE, TX_DATE, STATUS)
VALUES ('ACC10002', 'SMITH', 450.00, 'CR', CURRENT DATE, 'NORMAL');

INSERT INTO Z88116.BANK_TRANSACTIONS (ACCOUNT_ID, CUSTOMER_NAME, TX_AMOUNT, TX_TYPE, TX_DATE, STATUS)
VALUES ('ACC10003', 'YURDUGUL', 25000.00, 'DR', CURRENT DATE, 'NORMAL');

UPDATE Z88116.BANK_TRANSACTIONS 
SET STATUS = 'FLAGGED' 
WHERE TX_TYPE = 'DR' AND TX_AMOUNT > 10000.00;

SELECT ACCOUNT_ID, CUSTOMER_NAME, TX_AMOUNT, TX_TYPE, TX_DATE, STATUS 
FROM Z88116.BANK_TRANSACTIONS 
WHERE STATUS = 'FLAGGED';